src/components/common/index.ts
src/components/common/molecules/AppContainer.tsx
src/index.ts

AppContainer component displaying a background image on screens wider than 800px.
Closes #52

AppContainer

---

src/components/common/molecules/Banner.tsx

Just a small cleanup on the banner, old version was not working as expected.

fix: small banner cleanup

---

src/screens/SettingsScreen.tsx

Adding optional back label to settings screen. Will default to _Back_ if none is given.

feat: optional back label

---

package-lock.json
src/resources/language/en.json
src/resources/language/no.json
src/screens/FeedbackScreen.tsx
src/screens/OnBoardingScreen.tsx
src/screens/SettingsScreen.tsx

Added support for norwegian language in feedback and settings screen. Onboarding screen now can use custom submit function.
Also cherrypicked changes to FeedbackScreen from settingsscreen-redesign branch

Onboarding screen change / language support

---

package-lock.json
package.json
src/screens/FeedbackScreen.tsx

Closes https://github.com/equinor/mad-expense-and-pay-app/issues/249 and https://github.com/equinor/mad-expense-and-pay-app/issues/238

fix: keyboard issues in feedback screen

---

src/index.ts

Exporting enums from app insights from index.ts

chore: export enums from index

---

src/components/authentication/LoginButton.tsx

Closes #141 and https://github.com/equinor/mad-project-pleasemove/issues/326

fix: "Login" -> "Log in"

---

src/components/common/atoms/Typography.tsx

this will not affect Typography components without a onpress prop

Typography onpress

---

src/components/authentication/LoginButton.tsx
src/screens/LoginScreen.tsx
src/services/appInsights.ts
src/services/auth.ts
src/services/departmentId.ts

- Implemented a new feature to fetch the department ID
- Added the ability to log in using the fetched department ID
- Added a new prop useDepartmentId in the LoginButton component to enable or disable this feature
By setting the _useDepartmentId_ prop to true in the LoginButton component, users can now opt to utilize the department ID for the login process, providing additional flexibility and enhancing the overall user experience.

Fetching departmend id and track it

---

package-lock.json
package.json
src/actions/departmentId.ts
src/components/authentication/LoginButton.tsx
src/reducers/departmentId.ts
src/reducers/index.ts
src/screens/LoginScreen.tsx
src/services/appInsights.ts
src/services/auth.ts
src/services/configStore.ts
src/services/departmentId.ts
src/services/departmentIdStorage.ts
src/store/index.ts

- Store department in Mobile storage
- Individual app settings
- Promise-based dept. ID fetching
- Fetch everytime authenticateSilently gets called

Department id fetch feature

---

src/components/common/atoms/DataField.tsx
src/index.ts
src/resources/language/en.json
src/resources/language/no.json
src/screens/CreateIncidentScreen.tsx
src/screens/FeedbackScreen.tsx
src/utils/CreateIncident.ts

Created an alternative to Feedback Screen which creates a ticket in Service Now from the user. Similarly designed, with a few changes and improvements. Some wording may be subject to change so don't focus too much on the text strings.

Create incident screen

---

package-lock.json
package.json

Updated packages to versions compatible with Expo SDK 48.
Closes #158

fix(deps)!: Add compatibility with Expo SDK 48

---

package-lock.json
package.json

Updated packages to versions compatible with Expo SDK 49.
Closes #160

fix(deps)!: Add compatibility with Expo SDK 49

---

src/resources/language/en.json
src/resources/language/no.json
src/screens/SettingsScreen.tsx

feat: more spaces between the texts. Improved wording

---

README.md
src/components/common/atoms/Accordion.tsx
src/components/common/atoms/Button.tsx
src/components/common/atoms/Checkbox.tsx
src/components/common/atoms/DataField.tsx
src/components/common/atoms/IconButton.tsx
src/components/common/atoms/Radiobutton.tsx
src/components/common/atoms/SimpleInfoItem.tsx
src/components/common/atoms/Spinner.tsx
src/components/common/atoms/TextLink.tsx
src/components/common/atoms/Typography.tsx
src/components/common/atoms/textInputWithDoneButton/DoneButtonInputAccessoryView.tsx
src/components/common/atoms/textInputWithDoneButton/TextInputWithDoneButton.tsx
src/components/common/molecules/AppContainer.tsx
src/components/common/molecules/Banner.tsx
src/components/common/molecules/DetailsTable.tsx
src/components/common/molecules/NavigationList.tsx
src/components/common/molecules/SettingsButton.tsx

Added deprecation tags to all atoms and molecules

chore: add deprecation tags

---

package.json

- Add patch version range dependency to react native

fix(deps): fix peer dependency issues for newer expo versions

---

package-lock.json
package.json
src/components/common/organisms/ServiceMessage.tsx
src/services/BaseAPIServices.ts

Fixes two high vulnerabilities:
https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459
https://security.snyk.io/vuln/SNYK-JS-CRYPTOJS-6028119

fix(deps): axios fix snyk vulnerability

---

package-lock.json
package.json

- Upgrade peer dep of expo to any minor version of SDK 51
- Upgrade peer dep of react native to any patch version of 0.74
- Ensure no deprecated functionality is in codebase

Upgrade to require expo SDK 51

---

package-lock.json
package.json

fix: Upgrade dependencies

---

docs/AppInsights/AppInsights.md
src/components/common/organisms/ServiceMessage.tsx
src/screens/ReleaseNoteScreen.tsx

closes https://github.com/equinor/mad-team/issues/520

fix: update mad api base url
